#!/bin/sh
set -e
rootdir=$(pwd)
[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
mkdir -p /var/tmp/dist
cd /var/tmp/dist
tar xf $rootdir/[% c('input_files_by_name/libgpg-error') %]
export PATH="/var/tmp/dist/libgpg-error/bin:$PATH"
cd $rootdir
distdir=/var/tmp/dist/[% project %]
mkdir -p $distdir
tar xf [% project %]-[% c('version') %].tar.bz2
cd [% project %]-[% c('version') %]
[% IF c("var/osx") -%]
# our compiler does not like -g
sed -i 's/ac_cv_prog_cc_g=yes/ac_cv_prog_cc_g=no/' configure
[% END -%]
./configure --prefix=$distdir [% c("var/configure_opt") %][% IF c('var/windows') %] --enable-static --disable-shared[% END %]
make -j4
make prefix=$distdir install
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
