#!/bin/sh
set -e
rootdir=$(pwd)
distdir="$rootdir/dist/[% project %]"
mkdir -p "$distdir"
ar vx [% c('input_files_by_name/SDK') %]
tar xzf data.tar.gz
mv usr/lib/apple/SDKs "$distdir/SDK"
tar xf [% c('input_files_by_name/clang') %]
mv x-tools "$distdir"
cd "$rootdir/dist"
[% c('tar', {
   tar_src => [ project ],
   tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
}) %]
