#!/bin/bash
[% c("var/set_default_env") -%]

tar xf [% project %]-[% c('version') %].tar.gz
tar xf [% c('input_files_by_name/libotr') %]
mv libotr/[% c('var/lib_glob') %] [% project %]-[% c('version') %]/chrome/content/
[% IF c('var/windows') -%]
mv -f [% project %]-[% c('version') %]/chrome/content/libotr-*.dll \
      [% project %]-[% c('version') %]/chrome/content/otr.dll
[% END -%]
[% SET src_dir=project _ '-' _ c('version');
   c('tar', {
        tar_src => [src_dir],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
