#!/bin/sh
set -e
tar xf [% c('input_files_by_name/instantbird') %]
cd instantbird/extensions
tar xf ../../[% c('input_files_by_name/ctypes-otr') %]
mv ctypes-otr* 'ctypes-otr@tormessenger'
tar xf ../../[% c('input_files_by_name/tor-launcher') %]
mv tor-launcher-*/src tor-launcher@torproject.org
rm -Rf tor-launcher-*
mkdir -p tor-launcher@torproject.org/TorBrowser/Data
tar xf ../../[% c('input_files_by_name/tor-browser') %]
mv tor-browser_en-US/Browser/TorBrowser/Tor tor-launcher@torproject.org/TorBrowser/Tor
mv tor-browser_en-US/Browser/TorBrowser/Data/Tor tor-launcher@torproject.org/TorBrowser/Data/Tor
rm -Rf tor-browser_en-US
cd ../..
mv instantbird tor-messenger-[% c("version") %]
[% SET src_dir=project _ '-' _ c('version');
   c('tar', {
        tar_src => [src_dir],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
