#!/bin/sh
set -e

[% IF c("var/osx");
     INCLUDE build.osx;
     STOP;
   END -%]

rootdir=$(pwd)

mkdir bundle
[% IF c("var/windows") -%]
7z x -y -obundle [% c('input_files_by_name/instantbird') %]
mv bundle/instantbird bundle/Browser
[% ELSE -%]
mkdir bundle/Browser
tar xf [% c('input_files_by_name/instantbird') %] -C bundle/Browser --strip 1
[% END -%]
find bundle/Browser -exec touch -m -t $(date -d @[% c('timestamp') %] +%Y%m%d%H%M) {} \;

[% IF c("var/linux") -%]
# remove non reproducible files (FIPS-140)
# Tor Browser removes them too
rm -f bundle/Browser/*.chk
[% END -%]

mkdir bundle/Browser/TorBrowser
tar xf [% c('input_files_by_name/bundle-data') %]
[% IF c("var/linux") -%]
mv Bundle-Data/linux/* bundle/Browser/TorBrowser/
[% ELSE -%]
mv Bundle-Data/windows/* bundle/Browser/TorBrowser/
[% END -%]

[% IF c("var/linux") %]
tar xf [% c('input_files_by_name/gcc') %]
chmod 755 start-tor-messenger start-tor-messenger.desktop execdesktop

cp start-tor-messenger.desktop bundle/
mv start-tor-messenger.desktop bundle/Browser/
mv start-tor-messenger bundle/Browser/
mv execdesktop bundle/Browser/

mkdir -p bundle/Browser/lib
cp -L gcc/lib[% c('arch') == 'x86_64' ? '64' : '32' %]/libstdc++.so.6 bundle/Browser/lib/
[% END %]

cp cert_override.txt bundle/Browser/TorBrowser/Data/Browser/profile.default/

cd bundle/Browser/TorBrowser/Data/Browser/profile.default/
mkdir extensions
cd extensions/
tar xf ../../../../../../../[% c('input_files_by_name/ctypes-otr') %]
mv ctypes-otr* 'ctypes-otr@tormessenger'

mkdir tor-launcher@torproject.org
7z x -y -otor-launcher@torproject.org ../../../../../../../[% c('input_files_by_name/tor-launcher') %]
cat $rootdir/Bundle-Data/PTConfigs/bridge_prefs.js >> \
        tor-launcher@torproject.org/defaults/preferences/prefs.js

[% IF c("var/windows") -%]
7z x ../../../../../../../[% c('input_files_by_name/tor-browser') %]
mv \$_OUTDIR tor-browser_en-US
cp -pf tor-browser_en-US/Browser/libssp-0.dll tor-browser_en-US/Browser/TorBrowser/Tor/

[% ELSE -%]
tar xf ../../../../../../../[% c('input_files_by_name/tor-browser') %]

[% END -%]
sed -i 's/^SocksPort .*/SocksPort [% c("var/tor_socks_port") %]/' tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc-defaults
sed -i 's/^ControlPort .*/ControlPort [% c("var/tor_control_port") %]/' tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc-defaults

[% IF c("var/windows") -%]
# use meek in standalone mode: https://lists.torproject.org/pipermail/tor-dev/2015-November/009887.html
sed -i 's/\(ClientTransportPlugin meek exec\) [^ ]\+ [^ ]\+ -- /\1 /' tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc-defaults
rm -f  tor-browser_en-US/Browser/TorBrowser/Tor/PluggableTransports/meek-client-torbrowser.exe
[% ELSE -%]
# use meek in standalone mode: https://lists.torproject.org/pipermail/tor-dev/2015-November/009887.html
sed -i 's/\(ClientTransportPlugin meek exec\) [^ ]\+ -- /\1 /' tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc-defaults
rm -f  tor-browser_en-US/Browser/TorBrowser/Tor/PluggableTransports/meek-client-torbrowser
[% END -%]

cd ../../../../../../

mv Browser/TorBrowser/Data/Browser/profile.default/extensions/tor-browser_en-US/Browser/TorBrowser/Tor Browser/TorBrowser/
cp Browser/TorBrowser/Data/Browser/profile.default/extensions/tor-browser_en-US/Browser/TorBrowser/Data/Tor/* Browser/TorBrowser/Data/Tor/

rm -Rf Browser/TorBrowser/Data/Browser/profile.default/extensions/tor-browser_en-US
cd ..

mv bundle tor-messenger
[% IF c('var/windows') -%]
makensis tor-messenger.nsi

tar xf $rootdir/[% c('input_files_by_name/python-future') %]
cd $(echo [% c('input_files_by_name/python-future') %] | sed s/\.tar\.gz$//)
python setup.py install --user
cd ..

tar xf $rootdir/[% c('input_files_by_name/python-pefile') %]
cd $(echo [% c('input_files_by_name/python-pefile') %] | sed s/\.tar\.gz$//)
python setup.py install --user
cd ..

mv tor-messenger-install.exe tor-messenger-install-tmp.exe
python pe_checksum_fix.py
mv tor-messenger-install-tmp2.exe tor-messenger-install.exe
rm tor-messenger-install-tmp.exe
mv tor-messenger-install.exe [% dest_dir _ '/' _ c('filename') %]
[% ELSE -%]
[% c('tar', {
        tar_src => [ 'tor-messenger' ],
        tar_args => '-cJf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
[% END -%]
