#!/bin/bash

TM_START_PROG="$(grep '^X-TorMessenger-ExecShell' $1 | tail -1 | sed 's/^X-TorMessenger-ExecShell=//' | sed 's/%.//')"

shift

if [ "$#" -ge 1 ]
then
  echo "Launching '${TM_START_PROG} $@'..."
else
  echo "Launching '${TM_START_PROG}'..."
fi

eval "${TM_START_PROG} $@"
