#!/bin/bash
[% c("var/set_default_env") -%]

distdir="/var/tmp/dist/[% project %]"
mkdir -p "$distdir"
[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf $rootdir/[% project %]-[% c('version') %].tar.bz2
cd /var/tmp/build/[% project %]-[% c('version') %]
[% IF c("var/osx") -%]
cp $rootdir/lock-obj-pub.x86_64-apple-darwin14.0.0.h src/syscfg/lock-obj-pub.darwin10.h
echo 'int main() {}' > src/gen-posix-lock-obj.c
[% END -%]
export SOURCE_DATE_EPOCH=$(stat -c %Y ChangeLog)
./configure --prefix="$distdir" [% c("var/configure_opt") %] --enable-static --disable-shared
[% IF c("var/osx") -%]
  export LD_PRELOAD=[% c("var/faketime_path") %]
  export FAKETIME="[% USE date; GET date.format(c('timestamp'), format = '%Y-%m-%d %H:%M:%S') %]"
[% END -%]
make -j4
make prefix="$distdir" install
[% IF c("var/osx") -%]
  unset LD_PRELOAD
[% END -%]
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
