#!/bin/sh
set -e
distdir="/tmp/dist/[% project %]"
mkdir -p "$distdir"
[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
tar xf [% project %]-[% c('version') %].tar.bz2
cd [% project %]-[% c('version') %]
./configure --prefix="$distdir" [% c("var/configure_opt") %][% IF c('var/windows') %] --enable-static --disable-shared[% END %]
make -j4
make prefix="$distdir" install
cd /tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
