#!/bin/sh
set -e
distdir="/tmp/dist/[% project %]"
mkdir -p "$distdir"
tar xf [% project %]-[% c('version') %].tar.bz2
cd [% project %]-[% c('version') %]
./configure --prefix="$distdir"
make -j4
make prefix="$distdir" install
cd /tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
