#!/bin/sh
set -e
rootdir=$(pwd)

export SHELL=/bin/sh
export HOME=$rootdir
export MOZ_BUILD_DATE=$(date -d @[% c('timestamp') %] +%Y%m%d%H%M%S)
export SOURCE_DATE_EPOCH=[% c('timestamp') %]

[% IF c('var/osx') -%]
[% pc('gcc', 'var/setup', { compiler_tarfile => c('input_files_by_name/gcchost') }) %]
ln -s /var/tmp/dist/gcc/bin/gcc /var/tmp/dist/gcc/bin/cc
[% END -%]

[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]

mkdir -p /var/tmp/dist
cd /var/tmp/dist

[% IF c("var/linux") -%]
tar xf $rootdir/[% c('input_files_by_name/python') %]
export PATH="/var/tmp/dist/python/bin:$PATH"
tar xf $rootdir/[% c('input_files_by_name/binutils') %]
export PATH="/var/tmp/dist/binutils/bin:$PATH"
[% END -%]

# LD_BIND_NOW needed to avoid this error:
# undefined symbol: _ZNSt14error_categoryD2Ev
export LD_BIND_NOW=1

[% IF c("var/osname") == "linux-i686" -%]
export LDFLAGS=-m32
export CFLAGS=-m32
export CC='gcc -m32'
[% END -%]

[% IF c("var/linux") -%]
mkdir -p /var/tmp/dist/yasm/bin
ln -s /usr/bin/yasm-1 /var/tmp/dist/yasm/bin/yasm
export PATH="/var/tmp/dist/yasm/bin:$PATH"
[% END -%]

cd $rootdir
mkdir /var/tmp/build
tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.[% c('compress_tar') %]

mkdir moz
cd moz
tar xf $rootdir/[% c('input_files_by_name/mozilla') %]
mv mozilla-* /var/tmp/build/[% project %]-[% c('version') %]/mozilla

cd /var/tmp/build/[% project %]-[% c('version') %]

for patch in $(ls -1 $rootdir/*.patch | sort)
do
  git apply -p1 < $patch
done

echo '[% c("var/tormessenger_version") %]' > im/config/version.txt

cp $rootdir/[% c('input_files_by_name/mozconfig') %] .mozconfig
echo ac_add_options --with-tor-browser-version='[% c("var/tormessenger_version") %]' >> .mozconfig

./mozilla/mach build
./mozilla/mach package

mkdir -p [% dest_dir _ '/' _ c('filename') %]
mv obj-*/dist/instantbird-*.[% c('var/archive_suffix') %] [% dest_dir _ '/' _ c('filename') %]/instantbird.[% c('var/archive_suffix') %]
