#!/bin/sh
set -e
rootdir=$(pwd)

tar xf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]

if ls -1 $rootdir/*.patch > /dev/null 2>&1
then
    for patch in $(ls -1 $rootdir/*.patch | sort)
    do
        git apply -p1 < $patch
    done
fi

cd ..

[% SET src_dir=project _ '-' _ c('version');
    c('tar', {
        tar_src => [src_dir],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
