#!/bin/bash
[% c("var/set_default_env") -%]

tar xf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]

# Initialize a git repo here so that the patches aren't attempting to apply
# against basedir, since our temporary working dir is a subdir of it.
git init
for patch in $(ls -1 $rootdir/*.patch | sort)
do
  git apply -p1 < $patch
done
rm -rf .git

cd ..

[% SET src_dir=project _ '-' _ c('version');
    c('tar', {
        tar_src => [src_dir],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
