#!/bin/bash
[% c("var/set_default_env") -%]

tar xf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]

for patch in $(ls -1 $rootdir/*.patch | sort)
do
  git apply -p1 < $patch
done

cd ..

[% SET src_dir=project _ '-' _ c('version');
    c('tar', {
        tar_src => [src_dir],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
