#!/bin/sh
set -e
distdir=/var/tmp/dist/[% project %]
tar xf [% project %]-[% c("version") %].tar.bz2
cd [% project %]-[% c("version") %]
./configure --prefix=$distdir [% c("var/configure_opt") %]
make -j4
make install
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
