#!/bin/sh
set -e
rootdir=$(pwd)
mkdir bundle

[% IF c("var/windows") -%]
7z x -y -obundle [% c('input_files_by_name/thunderbird') %]
mv bundle/thunderbird bundle/Mail
[% ELSE -%]
mkdir bundle/Mail
tar xf [% c('input_files_by_name/thunderbird') %] -C bundle/Mail --strip 1
[% END -%]

chmod 755 start-tor-mail
mv start-tor-mail bundle/

mkdir bundle/Mail/defaults/profile/
mv user.js bundle/Mail/defaults/profile/

cd bundle/Mail/extensions
mkdir castironthunderbirdclub@torproject.org
7z x -y -ocastironthunderbirdclub@torproject.org $rootdir/[% c('input_files_by_name/torbirdy') %]
mkdir tor-launcher@torproject.org
7z x -y -otor-launcher@torproject.org $rootdir/[% c('input_files_by_name/tor-launcher') %]
mkdir -p tor-launcher@torproject.org/TorBrowser/Data

[% IF c("var/windows") -%]
7z x ../../../[% c('input_files_by_name/tor-browser') %]
mv \$_OUTDIR tor-browser_en-US
[% ELSE -%]
tar xf ../../../[% c('input_files_by_name/tor-browser') %]
[% END -%]

sed -i 's/^SocksPort .*/SocksPort [% c("var/tor_socks_port") %]/' tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc-defaults
sed -i 's/^ControlPort .*/ControlPort [% c("var/tor_control_port") %]/' tor-browser_en-US/Browser/TorBrowser/Data/Tor/torrc-defaults
mv tor-browser_en-US/Browser/TorBrowser/Tor tor-launcher@torproject.org/TorBrowser/Tor
mv tor-browser_en-US/Browser/TorBrowser/Data/Tor tor-launcher@torproject.org/TorBrowser/Data/Tor
rm -Rf tor-browser_en-US
cd $rootdir
mv bundle tor-mail
[% c('tar', {
        tar_src => [ 'tor-mail' ],
        tar_args => '-cJf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
