#!/bin/bash

TMB_START_PROG="$(grep '^X-TorMail-ExecShell' $1 | tail -1 | sed 's/^X-TorMail-ExecShell=//' | sed 's/%.//')"

shift

if [ "$#" -ge 1 ]
then
  echo "Launching '${TMB_START_PROG} $@'..."
else
  echo "Launching '${TMB_START_PROG}'..."
fi

eval "${TMB_START_PROG} $@"
