#!/bin/bash
[% c("var/set_default_env") -%]

[% pc(c('var/compiler'), 'var/setup', { compiler_tarfile => c('input_files_by_name/' _ c('var/compiler')) }) %]
mkdir -p /var/tmp/dist
cd /var/tmp/dist
tar xf $rootdir/[% c('input_files_by_name/libgpg-error') %]
export PATH="/var/tmp/dist/libgpg-error/bin:$PATH"
tar xf $rootdir/[% c('input_files_by_name/libgcrypt') %]
export PATH="/var/tmp/dist/libgcrypt/bin:$PATH"
cd $rootdir
distdir=/var/tmp/dist/[% project %]
mkdir -p /var/tmp/build
tar -C /var/tmp/build -xf libotr-[% c('version') %].tar.gz
cd /var/tmp/build/libotr-[% c('version') %]
export SOURCE_DATE_EPOCH=$(stat -c %Y ChangeLog)
./configure --prefix=$distdir [% c("var/configure_opt") %]
make -j4 [% IF c("var/windows") %]LDFLAGS='-no-undefined -lssp'[% END %]
make prefix=$distdir install
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
