#!/bin/sh
set -e
tar xvf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]
patch -d src -p1 < ../topdir.patch
[% IF c("var/tor_control_port") -%]
patch -p1 < ../controlport.patch
[% END -%]
[% IF c("var/tor-mail") -%]
cp ../torbirdy.png src/chrome/skin/tbb-logo.png
[% END -%]
[% IF c("var/tor-messenger") -%]
cp ../messenger.png src/chrome/skin/tbb-logo.png
[% END -%]
patch -p1 < ../logo.patch
make package
mv pkg/*.xpi [% dest_dir _ '/' _ c('filename') %]
