#!/bin/bash
[% c("var/set_default_env") -%]
tar xvf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]
patch -p1 < ../0001-Workaround-for-chrome-uri-skin-path.patch
[% IF c("var/tor_control_port") -%]
patch -p1 < ../controlport.patch
[% END -%]
[% IF c("var/tor-messenger") -%]
cp ../tm-logo.svg src/chrome/skin/tbb-logo.svg
[% END -%]
make package
mv pkg/*.xpi [% dest_dir _ '/' _ c('filename') %]
