#!/bin/sh
set -e
distdir=/var/tmp/dist/binutils
tar xf [% project %]-[% c("version") %].tar.bz2
cd [% project %]-[% c("version") %]
[% IF c('var/windows') -%]
# XXX: This is needed due to bug 10102.
sed 's/= extern_rt_rel_d;/= extern_rt_rel_d;\n  memset (extern_rt_rel_d, 0, PE_IDATA5_SIZE);/' -i ld/pe-dll.c
# Needed for the hardening...
patch -p1 < ../enable-reloc-section-ld.patch
# specify-timestamp patch from Stephen Kitt <steve@sk2.org>
# https://anonscm.debian.org/cgit/collab-maint/binutils-mingw-w64.git/
patch -p2 < ../specify-timestamp.patch
[% END -%]
./configure --prefix=$distdir [% c('var/configure_opt') %]
make -j4
make install
cd /var/tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
