#!/bin/sh
set -e
distdir=/tmp/dist/binutils
tar xf [% project %]-[% c("version") %].tar.bz2
cd [% project %]-[% c("version") %]
./configure --prefix=$distdir --disable-multilib --enable-gold
make -j4
make install
cd /tmp/dist
[% c('tar', {
        tar_src => [ project ],
        tar_args => '-czf ' _ dest_dir _ '/' _ c('filename'),
        }) %]
