#!/bin/sh
set -e
tar xvf [% project %]-[% c('version') %].tar.gz
cd [% project %]-[% c('version') %]
patch -p1 < ../0001-Update-settings-for-Tor-Mail-builds.patch
make make-xpi
cd ..
mv -f torbirdy-[% c("version") %].xpi [% dest_dir _ '/' _ c('filename') %]
